config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :stocks

  root 'home#index'

  post "/", to: "home#index"

  get '/about' => "home#about"

  get '*path', :to => redirect('./404.html')
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  validates :ticker, presence: true, format: {without: /\s/}, uniqueness: { scope: :user }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stocks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  StockQuote::Stock.new(api_key: "#{ENV["stock_api_key"]}")
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    if params[:query] == ""

      @nothing = "Hey! You Forgot to Enter a Symbol"
    elsif params[:query]
        begin
        @stock = StockQuote::Stock.quote(params[:query])
        rescue => e
          @error = e
        end
    end
  end

  def about
  end

  def create
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :right_user, only: [:edit, :update, :show, :destroy]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)
    begin
      if StockQuote::Stock.quote(@stock.ticker)
        respond_to do |format|
          if @stock.save
            format.html { redirect_to @stock, notice: "Stock was successfully created." }
            format.json { render :show, status: :created, location: @stock }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @stock.errors, status: :unprocessable_entity }
          end
        end
      end
    rescue => e
      flash.now[:notice] = "This stock is not valid. #{e}"
      render :new
    end

  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stock
    begin
      @stock = Stock.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      redirect_to stocks_path, notice: "#{e}"
    end
  end

  # Only allow a list of trusted parameters through.
  def stock_params
    params.require(:stock).permit(:ticker, :user_id)
  end

  def right_user
    if @stock.user != current_user
      redirect_to stocks_path, notice: "You are not the right user"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/app/_flash.html.erb
<% flash.each do |type, msg| %>
<div class="alert alert-success alert-dismissible fade show <%= type %>"
     role="alert">
    <%= msg %>
    <button type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"></button>
</div>
<% end %>

app/views/app/_footer.html.erb
<center>Copyright 2021</center>

app/views/app/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Stock Market App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse"
         id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'View Stocks', stocks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Stock', new_stock_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
        </li>

        <% end %>


      </ul>
      <form class="d-flex">
        <input class="form-control me-2"
               type="search"
               placeholder="Search"
               aria-label="Search">
        <button class="btn btn-outline-success"
                type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
About

app/views/home/create.html.erb
<h1>Home#create</h1>

<%= form_with url: root_path, method: :post do |form| %>
<%= form.text_field :query, placeholder: "Enter Ticker Symbol", size: 30 %>
<%= form.submit "Search" %>
<% end %>

<% if params[:query].present? %>
<%= @stock.inspect %>
<br>
<br>
<%= params[:query] %>

<img src="<%= @url %>"
     alt="Tesla">


<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Stock Market App</title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible"
        content="IE=edge">
  <meta name="viewport"
        content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="reset_margin">
  <%= render 'app/navbar' %>
  <%= render 'app/flash' %>
  <br>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'app/footer' %>
</body>

</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
<% if stock.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

  <ul>
    <% stock.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :ticker %>
  <%= form.text_field :ticker %>
</div>

<div class="field">
  <%= form.text_field :user_id, value: current_user.id, type: :hidden %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Stock Portfolio</h1>

<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th>Company Name</th>
      <th>Ticker</th>
      <th>Price</th>
      <th>Market Cap</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
    <% if stock.user == current_user %>
    <% if stock.ticker
        begin
          @ticker = StockQuote::Stock.quote(stock.ticker)
        rescue => e
          @ticker.company_name = "N/A"
          @ticker.symbol = "N/A"
          @ticker.latest_price = "N/A"
          @ticker.market_cap = "N/A" %>
    <% end %>
    <% end %>
    <tr>
      <td><%= link_to @ticker.company_name, stock %></td>
      <td><%= @ticker.symbol %></td>
      <td>$<%= number_with_precision @ticker.latest_price, :precision => 2, :delimiter => "," %></td>
      <td>$<%= number_with_precision @ticker.market_cap, :precision => 0, :delimiter => "," %></td>
      <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
      <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>

    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker.upcase %>
</p>
<% ticker = StockQuote::Stock.quote(@stock.ticker) %>
<% logo = StockQuote::Stock.logo(@stock.ticker) %>
<img src="<%= logo.url %>"
     alt="<%= ticker.company_name %> logo">
<p>
  <strong>Company Name:</strong>
  <%= ticker.company_name %>
</p>
<p>
  <strong>Symbol:</strong>
  <%= ticker.symbol %>
</p>
<p>
  <strong>Latest Price:</strong>
  $<%= number_with_precision ticker.latest_price, :precision => 2, :delimiter => "," %>
</p>
<p>
  <strong>Market Cap:</strong>
  $<%= number_with_precision ticker.market_cap, :precision => 0, :delimiter => "," %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>